-- Seed new library items into Supabase.
-- Run this in the Supabase SQL Editor after the inventory columns are in place.

INSERT INTO public.library_items (
  title,
  author,
  item_type,
  keywords,
  description,
  item_number,
  is_available,
  total_copies,
  available_copies,
  created_at,
  updated_at
)
VALUES
  (
    'Agriculture, Food and Nutrition',
    'Nekesha T. Wafullah and Kuria A. Munene',
    'book',
    ARRAY['Food Systems', 'Nutrition', 'Policy', 'Agricultural Economics']::text[],
    'Explores the intersection of agricultural production and human nutritional health.',
    NULL,
    true,
    3,
    3,
    now(),
    now()
  ),
  (
    'Agriculture, Economics and Resource Management',
    'Milton M. Snodgrass',
    'book',
    ARRAY['Agribusiness', 'Resource Allocation', 'Farming Economics']::text[],
    'A study of economic principles applied to the management of agricultural resources.',
    NULL,
    true,
    3,
    3,
    now(),
    now()
  ),
  (
    'Sustainable Tourism on a Finite Planet',
    'Megan Epler Wood',
    'book',
    ARRAY['Ecotourism', 'Sustainability', 'Global Policy']::text[],
    'Addresses environmental and business solutions for sustainable global tourism.',
    NULL,
    true,
    3,
    3,
    now(),
    now()
  ),
  (
    'Environmental Science: Earth as a Living Planet',
    'Daniel B. Botkin and Edward A. Keller',
    'book',
    ARRAY['Ecology', 'Sustainability', 'Biosphere']::text[],
    'An introductory text on how Earth functions as a biological and physical system.',
    NULL,
    true,
    3,
    3,
    now(),
    now()
  ),
  (
    'Engineering Economy',
    'Leland Blank',
    'book',
    ARRAY['Cost Analysis', 'Interest', 'Financial Engineering']::text[],
    'Focuses on the principles of economic analysis for engineering project decision-making.',
    NULL,
    true,
    3,
    3,
    now(),
    now()
  ),
  (
    'Programming Languages: Concepts and Constructs',
    'Ravi Sethi',
    'book',
    ARRAY['Syntax', 'Semantics', 'Compilers', 'Logic']::text[],
    'Covers the fundamental concepts behind the design and implementation of programming languages.',
    NULL,
    true,
    3,
    3,
    now(),
    now()
  ),
  (
    'Programming Massively Parallel Processors',
    'David B. Kirk and Wen-Mei W. Hwu',
    'book',
    ARRAY['GPU', 'CUDA', 'Parallel Computing', 'Performance']::text[],
    'A hands-on approach to programming many-core processors and GPU architectures.',
    NULL,
    true,
    3,
    3,
    now(),
    now()
  ),
  (
    'Introduction to Computer Programming and Logic Formulation Using C Language',
    'Marmelo V. Abante, Marygin E. Sarmiento, and Dan Michael A. Cortez',
    'book',
    ARRAY['C Language', 'Logic Formulation', 'Beginner Programming']::text[],
    'Foundational guide for beginners focusing on logic and C programming basics.',
    NULL,
    true,
    3,
    3,
    now(),
    now()
  ),
  (
    'Development of Game-Based Application for Learning Fundamentals of Programming',
    'Russel M. Zamora, Clarence A. Cuenca, and Janley Jude U. Acha',
    'thesis',
    ARRAY['Gamification', 'EdTech', 'Programming Logic']::text[],
    'A university thesis developing a gaming app to teach core programming concepts.',
    NULL,
    true,
    1,
    1,
    now(),
    now()
  ),
  (
    'Emotional Intelligence and College Adjustment Among Psychology Students',
    'Jahazel Yvon Amplayo, et al.',
    'thesis',
    ARRAY['Psychology', 'Emotional Intelligence', 'Student Adaptation']::text[],
    'A study on how EQ affects the academic and social transition of college students.',
    NULL,
    true,
    1,
    1,
    now(),
    now()
  ),
  (
    'Awareness, Attitude, and Practices on the Ban of Single-Use Plastics',
    'Myka C. Jabay, et al.',
    'thesis',
    ARRAY['Environmental Policy', 'Waste Management', 'Public Awareness']::text[],
    'Research on the effectiveness of plastic bans in local public markets.',
    NULL,
    true,
    1,
    1,
    now(),
    now()
  ),
  (
    'New Normal Learning: Coping Mechanisms of Engineering Students',
    'Tiras Kim M. Malingin, et al.',
    'thesis',
    ARRAY['Distance Learning', 'Engineering Education', 'Coping Strategies']::text[],
    'Analyzes how senior engineering students adapted to pandemic-era learning shifts.',
    NULL,
    true,
    1,
    1,
    now(),
    now()
  );